# generated by linuxdeploy-plugin-qt

# try to make Qt apps more "native looking", if possible
# see also https://github.com/AppImage/AppImageKit/issues/977#issue-462374883
# and https://github.com/AppImage/AppImageKit/issues/977#issue-462374883
case "${XDG_CURRENT_DESKTOP}" in
    *GNOME*|*gnome*|*XFCE*)
        export QT_QPA_PLATFORMTHEME=gtk2
        ;;
esac
